/* Generated by Cython 0.29.21 */

#ifndef __PYX_HAVE__ext
#define __PYX_HAVE__ext

#include "Python.h"

#ifndef __PYX_HAVE_API__ext

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C CppFoo a;
__PYX_EXTERN_C struct CyBar b;

#endif /* !__PYX_HAVE_API__ext */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initext(void);
#else
PyMODINIT_FUNC PyInit_ext(void);
#endif

#endif /* !__PYX_HAVE__ext */
